[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310', 'py311', 'py312']
skip-string-normalization = false
exclude = 'venv'

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
