"""empty message

Revision ID: aa3bf73c16c3
Revises: 908c204e5da8
Create Date: 2025-05-24 15:19:20.978439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3bf73c16c3'
down_revision = '908c204e5da8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parking_spot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vip', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_spot', schema=None) as batch_op:
        batch_op.drop_column('vip')

    op.drop_table('report')
    # ### end Alembic commands ###
