"""empty message

Revision ID: c47fa5b80fb6
Revises: 
Create Date: 2025-04-24 14:53:20.443719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c47fa5b80fb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('license_plate')
    )
    op.create_table('parking_spot',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('is_occupied', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('parking_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.String(length=20), nullable=True),
    sa.Column('spot_id', sa.Integer(), nullable=True),
    sa.Column('check_in_time', sa.DateTime(), nullable=True),
    sa.Column('check_out_time', sa.DateTime(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car.license_plate'], ),
    sa.ForeignKeyConstraint(['spot_id'], ['parking_spot.number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parking_session')
    op.drop_table('parking_spot')
    op.drop_table('car')
    # ### end Alembic commands ###
